server:
  port: 8484

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
            - Method=POST,GET,PATCH,DELETE
          filters:
            - RewritePath=/users/(?<remaining>.*), /$\{remaining}
            - name: CircuitBreaker
              args:
                name: userServiceCB
                fallbackUri: forward:/fallback/user
            - name: Retry
              args:
                retries: 3
                methods: POST,GET,PATCH,DELETE
                backoff:
                  firstBackoff: 100ms
                  maxBackoff: 1000ms
                  factor: 2

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification/**
          filters:
            - RewritePath=/notification/(?<remaining>.*), /$\{remaining}

  resilience4j:
    circuitbreaker:
      instances:
        userServiceCB:
          slidingWindowType: COUNT_BASED
          slidingWindowSize: 10
          failureRateThreshold: 50
          waitDurationInOpenState: 10s

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8686/eureka/