server:
  port: 8484

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: user-service
          uri: lb://USER-SERVICE  # Используем имя сервиса из Eureka
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users/(?<segment>.*), /users/$\{segment}
            - name: CircuitBreaker
              args:
                name: userServiceCB
                fallbackUri: forward:/fallback/user
            - name: Retry
              args:
                retries: 3
                methods: GET,POST

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web: DEBUG
    reactor.netty.http.client: DEBUG