server:
  port: 8484

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      httpclient:
        pool:
          max-idle-time: 30000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true  # Используем IP вместо hostname
    ip-address: 127.0.0.1    # Явно указываем локальный IP
    hostname: localhost       # Фиксируем hostname

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.client.discovery: TRACE