server:
  port: 8080

spring:
  application:
    name: user-service
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    username: postgres
    password: 12341234qQ
    url: jdbc:postgresql://localhost:5432/users
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      user:
        notifications: user-created-del-topic
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      enable:
        idempotence: true
    consumer:
      group-id: userAPP

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/